### ISSUE TITLE
Issue on page /direnv.html - explain what direnv is for in our specific application

### ISSUE THREAD

**Issue by christian-stepanek** [AWI-ESM/docs#1]
Great tutorial!

As a bit of explanation I would add a bit of text to the already available explanation:

old text: "[direnv](https://www.direnv.net/) allows you to specify particular actions your shell will perform when entering or exiting a particular directory."

new text (to be added after the old text): "In the case of AWI-ESM this functionality is used to enable a modeller to specify specific software environments for different model versions, simulations, or similar. This facilitates that settings, that are specifically necessary for one simulation or for one model version, but that should not be used for others, are automatically activated when entering the folder where model or simulation resides. In principle, direnv simplifies the process of updating your environment variables, modules, or other settings whenever you switch between simulations or model versions."

**Comment by pgierz** [comment]
I think this was addressed in the PR I already put in...? Closing.
