### ISSUE TITLE
Issue on page /direnv.html - clarify use of configuration files

### ISSUE THREAD

**Issue by christian-stepanek** [AWI-ESM/docs#2]
It is great that you give various possibilities of configuration files where the direnv-related commands can be placed. Maybe just add one line of text that clarifies that one can choose the configuration file and does not need to update both (I did it for bash_profile only).

**Comment by pgierz** [comment]
Hi Christian,

A hint: you can add as a comment or in the main text of the pull request "Closes #BLAH", and the linked issue is automatically finished.

Best
PG
